import 'package:flutter/material.dart';
import 'package:praktikum5/dashboard/cabe.dart';
import 'package:praktikum5/dashboard/kacang.dart';
import 'package:praktikum5/dashboard/rissol.dart';
import 'package:praktikum5/dashboard/seblak.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          HalamanUtama(),
        ]),
      ),
    );
  }
}

class HalamanUtama extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 896,
          height: 1495,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(),
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 896,
                  height: 1495,
                  decoration: BoxDecoration(
                    gradient: LinearGradient(
                      begin: Alignment(0.00, -1.00),
                      end: Alignment(0, 1),
                      colors: [
                        Color(0x005E8989),
                        Color(0x005E8989),
                        Color(0xFF5DC8A2)
                      ],
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 1334,
                child: Container(
                  width: 898,
                  height: 189,
                  decoration: BoxDecoration(
                    color: Color(0xFFEBF5EE),
                    borderRadius: BorderRadius.circular(35),
                    border: Border(
                      left: BorderSide(
                        strokeAlign: BorderSide.strokeAlignOutside,
                        color: Colors.black.withOpacity(0.699999988079071),
                      ),
                      top: BorderSide(
                        strokeAlign: BorderSide.strokeAlignOutside,
                        color: Colors.black.withOpacity(0.699999988079071),
                      ),
                      right: BorderSide(
                        strokeAlign: BorderSide.strokeAlignOutside,
                        color: Colors.black.withOpacity(0.699999988079071),
                      ),
                      bottom: BorderSide(
                        width: 1,
                        strokeAlign: BorderSide.strokeAlignOutside,
                        color: Colors.black.withOpacity(0.699999988079071),
                      ),
                    ),
                    boxShadow: [
                      BoxShadow(
                        color: Color(0x3F000000),
                        blurRadius: 4,
                        offset: Offset(0, 10),
                        spreadRadius: 3,
                      )
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 76,
                top: 364,
                child: Container(
                  width: 753,
                  height: 159,
                  decoration: ShapeDecoration(
                    color: Color(0xFFF6F6F6),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(30),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 276,
                top: 130,
                child: SizedBox(
                  width: 373,
                  height: 80,
                  child: Text(
                    'Lets Cook',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 75,
                      fontFamily: 'Libre Bodoni',
                      fontWeight: FontWeight.w400,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 96,
                top: 72,
                child: Transform(
                  transform: Matrix4.identity()
                    ..translate(0.0, 0.0)
                    ..rotateZ(-3.14),
                  child: Container(
                    width: 63,
                    height: 47,
                    decoration: BoxDecoration(
                      image: DecorationImage(
                        image: AssetImage(""),
                        fit: BoxFit.fill,
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 149,
                top: 390,
                child: Container(
                  width: 104,
                  height: 107,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: AssetImage('android/assets/seblak.jpeg'),
                      fit: BoxFit.fill,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 657,
                top: 467,
                child: ElevatedButton(
                  onPressed: () {
                    Navigator.push(
                      context,
                      MaterialPageRoute(builder: (context) => Seblak()),
                    );
                  },
                  // ====SEBLAK=====
                  child: Text(
                    'Lihat resep',
                    style: TextStyle(
                      fontSize: 25,
                      fontFamily: 'Playfair Display',
                      fontWeight: FontWeight.w700,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 293,
                top: 411,
                child: Text(
                  'Seblak Bandung',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 45,
                    fontFamily: 'Manuale',
                    fontWeight: FontWeight.w700,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: 76,
                top: 535,
                child: Container(
                  width: 753,
                  height: 159,
                  decoration: ShapeDecoration(
                    color: Color(0xFFFCFAFF),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(30),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 76,
                top: 1048,
                child: Container(
                  width: 753,
                  height: 159,
                  decoration: ShapeDecoration(
                    color: Color(0xFFFCFAFF),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(30),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 76,
                top: 877,
                child: Container(
                  width: 753,
                  height: 159,
                  decoration: ShapeDecoration(
                    color: Color(0xFFFCFAFF),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(30),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 76,
                top: 706,
                child: Container(
                  width: 753,
                  height: 159,
                  decoration: ShapeDecoration(
                    color: Color(0xFFFCFAFF),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(30),
                    ),
                  ),
                ),
              ),
    //KACANG PANJANG
              Positioned(
                left: 149,
                top: 555,
                child: Container(
                  width: 106.12,
                  height: 107,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: AssetImage(""),
                      fit: BoxFit.fill,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 285,
                top: 573,
                child: Text(
                  'Oseng Kacang Panjang',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 45,
                    fontFamily: 'Manuale',
                    fontWeight: FontWeight.w700,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: 285,
                top: 753,
                child: Text(
                  'Mango Smoothies',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 45,
                    fontFamily: 'Manuale',
                    fontWeight: FontWeight.w700,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: 293,
                top: 924,
                child: Text(
                  'Risol Mayo',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 45,
                    fontFamily: 'Manuale',
                    fontWeight: FontWeight.w700,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: 297,
                top: 1085,
                child: Text(
                  'Ayam geprek Sambel Ijo',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 45,
                    fontFamily: 'Manuale',
                    fontWeight: FontWeight.w700,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: 657,
                top: 644,
                child: ElevatedButton(
                  onPressed: () {
                    Navigator.push(
                      context,
                      MaterialPageRoute(builder: (context) => Kacang()),
                    );
                  },
                  //KACANG PANJANG//
                  child: Text(
                    'Lihat resep',
                    style: TextStyle(
                      fontSize: 25,
                      fontFamily: 'Playfair Display',
                      fontWeight: FontWeight.w700,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 657,
                top: 815,
                child: ElevatedButton(
                  onPressed: () {
                    Navigator.push(
                      context,
                      MaterialPageRoute(builder: (contxt) => rissol()),
                    );
                  },
                  child: Text(
                    'Lihat resep',
                    style: TextStyle(
                      fontSize: 25,
                      fontFamily: 'Playfair Display',
                      fontWeight: FontWeight.w700,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 657,
                top: 973,
                child: ElevatedButton(
                  onPressed: () {
                    Navigator.push(
                      context,
                      MaterialPageRoute(builder: (contect) => Cabe()),
                    );
                  },
                  child: Text(
                    'Lihat resep',
                    style: TextStyle(
                      color: Color(0xFF1C67AC),
                      fontSize: 25,
                      fontFamily: 'Playfair Display',
                      fontWeight: FontWeight.w700,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 657,
                top: 1150,
                child: Text(
                  'Lihat resep',
                  style: TextStyle(
                    color: Color(0xFF1C67AC),
                    fontSize: 25,
                    fontFamily: 'Playfair Display',
                    fontWeight: FontWeight.w700,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: 405,
                top: 1370,
                child: Container(
                  width: 135,
                  height: 88,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: AssetImage(''),
                      fit: BoxFit.fill,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 149,
                top: 1068,
                child: Container(
                  width: 104,
                  height: 104,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: AssetImage("android/assets/ayam.jpeg"),
                      fit: BoxFit.fill,
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
